
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 29 06:48:31 CST 2025
//----------------------------------------------------

package com.mycompany.back_compi1.Parsers.sHTTP;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int SITIO = 8;
  public static final int PAGINA = 9;
  public static final int SCL_TEXT = 3;
  public static final int BODY = 2;
  public static final int EOF = 0;
  public static final int DELETE = 7;
  public static final int error = 1;
  public static final int POST = 5;
  public static final int GET = 4;
  public static final int PATCH = 6;
}

