
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 28 19:38:27 CST 2025
//----------------------------------------------------

package com.mycompany.back_compi1.Parsers.sHTTP;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int AGREGAR = 6;
  public static final int SITIO = 12;
  public static final int ELIMINAR = 5;
  public static final int PAGINA = 13;
  public static final int BODY = 3;
  public static final int EOF = 0;
  public static final int CREAR = 4;
  public static final int DELETE = 11;
  public static final int MODIFICAR = 7;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int POST = 9;
  public static final int GET = 8;
  public static final int PATCH = 10;
}

