
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 29 07:28:33 CST 2025
//----------------------------------------------------

package com.mycompany.back_compi1.Parsers.sCL;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int AGREGAR = 4;
  public static final int SITIO = 7;
  public static final int ELIMINAR = 5;
  public static final int PAGINA = 8;
  public static final int EOF = 0;
  public static final int CREAR = 3;
  public static final int MODIFICAR = 6;
  public static final int ID = 2;
  public static final int error = 1;
}

